# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IOCamRegister.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(338, 135)
        self.NameEntry = QtWidgets.QLineEdit(Form)
        self.NameEntry.setGeometry(QtCore.QRect(70, 50, 191, 21))
        self.NameEntry.setObjectName("NameEntry")
        self.NameLabel = QtWidgets.QLabel(Form)
        self.NameLabel.setGeometry(QtCore.QRect(120, 20, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.NameLabel.setFont(font)
        self.NameLabel.setObjectName("NameLabel")
        self.DoneButton = QtWidgets.QPushButton(Form)
        self.DoneButton.setGeometry(QtCore.QRect(120, 90, 75, 23))
        self.DoneButton.setObjectName("DoneButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.NameLabel.setText(_translate("Form", "Patient Name"))
        self.DoneButton.setText(_translate("Form", "Done"))
